### ISSUE TITLE
not working with firefox quantum

### ISSUE THREAD

**Issue by markmark1** [jfitzell/mozilla-keychain#89] opened 2017-10-23 23:38 UTC
its not working with firefox quantum or beta pls fix

**Comment by jfitzell** [comment] 2017-10-24 06:07
Duplicate of #88

Mozilla has deprecated the necessary interfaces as of FF 57 and has yet to provide an alternative. I'm afraid your only solution at the moment is to stick with FF 56.

**Closed as completed by jfitzell** 2017-10-24 06:07 UTC
